package jace.scholarwiki.model;

import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class WikiPage {
    private Long id;
    private String title;
    private String arxivId;
    private String authors;
    private LocalDate published;
    private String abstractText;
    private String wikiMd;
    private String tags;
    private LocalDateTime autoGeneratedAt;
    private LocalDateTime manualUpdatedAt;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
