server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paismart
    username: root
    password: PaiSmart2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-local.sql

  data:
    redis:
      host: localhost
      port: 6379
      password: PaiSmart2025
      timeout: 3000

logging:
  level:
    jace.scholarwiki: DEBUG
    org.springframework.jdbc: DEBUG
