package jace.scholarwiki.controller;

import jace.scholarwiki.model.ChunkSearchResult;
import jace.scholarwiki.model.SearchResult;
import jace.scholarwiki.model.WikiPage;
import jace.scholarwiki.repository.WikiPageRepository;
import jace.scholarwiki.service.WikiService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/papers")
@RequiredArgsConstructor
public class PaperController {

    private final WikiService wikiService;
    private final WikiPageRepository wikiPageRepository;

    /**
     * POST /api/v1/papers
     * Submit a fully-processed paper note with wiki markdown.
     * wikiMd should contain {#id} anchors for chunk-level vectorization.
     */
    @PostMapping
    public ResponseEntity<Map<String, Object>> submitPaper(
            @RequestBody Map<String, Object> body,
            @RequestAttribute("userId") Long userId) {

        String arxivId = (String) body.get("arxivId");
        if (arxivId == null || arxivId.isBlank()) {
            return ResponseEntity.badRequest().body(Map.of("error", "arxivId must not be blank"));
        }

        String title = (String) body.getOrDefault("title", "");
        String authors = (String) body.getOrDefault("authors", "");
        String publishedStr = (String) body.getOrDefault("published", "");
        String abstractText = (String) body.getOrDefault("abstractText", "");
        String wikiMd = (String) body.getOrDefault("wikiMd", "");
        String tags = (String) body.getOrDefault("tags", "");

        // Save wiki page
        WikiPage page = new WikiPage();
        page.setTitle(title);
        page.setArxivId(arxivId);
        page.setAuthors(authors);
        page.setAbstractText(abstractText);
        page.setWikiMd(wikiMd);
        page.setTags(tags);
        if (!publishedStr.isBlank()) {
            try {
                page.setPublished(LocalDate.parse(publishedStr));
            } catch (Exception ignored) {
            }
        }
        page.setAutoGeneratedAt(LocalDateTime.now());
        page.setCreatedAt(LocalDateTime.now());
        page.setUpdatedAt(LocalDateTime.now());
        wikiService.saveWikiPage(page);

        // Process chunks: parse by {#id} anchors, save, vectorize
        wikiService.processChunks(arxivId, wikiMd);

        return ResponseEntity.ok(Map.of(
                "status", "SAVED",
                "arxivId", arxivId
        ));
    }

    /**
     * GET /api/v1/papers/{arxivId}
     * Get a paper's metadata and wiki markdown.
     */
    @GetMapping("/{arxivId}")
    public ResponseEntity<Map<String, Object>> getPaper(@PathVariable String arxivId) {
        WikiPage page = wikiPageRepository.findByArxivId(arxivId).orElse(null);
        if (page == null) {
            return ResponseEntity.notFound().build();
        }

        Map<String, Object> result = new HashMap<>();
        result.put("arxivId", page.getArxivId());
        result.put("title", page.getTitle());
        result.put("authors", page.getAuthors());
        result.put("published", page.getPublished());
        result.put("abstract", page.getAbstractText());
        result.put("wikiMd", page.getWikiMd());
        result.put("tags", page.getTags());
        result.put("generatedAt", page.getAutoGeneratedAt());

        return ResponseEntity.ok(result);
    }

    /**
     * GET /api/v1/papers/{arxivId}/md
     * Get raw wiki markdown.
     */
    @GetMapping("/{arxivId}/md")
    public ResponseEntity<String> getPaperMarkdown(@PathVariable String arxivId) {
        WikiPage page = wikiPageRepository.findByArxivId(arxivId).orElse(null);
        if (page == null) {
            return ResponseEntity.notFound().build();
        }

        return ResponseEntity.ok()
                .contentType(MediaType.parseMediaType("text/markdown;charset=UTF-8"))
                .body(page.getWikiMd());
    }

    /**
     * GET /api/v1/papers/search?q=xxx&mode=vector&page=0&size=20
     * Vector search across paper chunks. Returns the most relevant chunks.
     */
    @GetMapping("/search")
    public ResponseEntity<SearchResult<ChunkSearchResult>> search(
            @RequestParam String q,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {

        SearchResult<ChunkSearchResult> result = wikiService.vectorSearch(q, page, size);
        return ResponseEntity.ok(result);
    }
}
