package jace.scholarwiki.repository;

import jace.scholarwiki.model.WikiPage;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@Repository
public class WikiPageRepository {

    private final JdbcTemplate jdbcTemplate;

    public WikiPageRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public Long insert(WikiPage page) {
        String sql = "INSERT INTO wiki_pages (title, arxiv_id, authors, published, abstract_text, wiki_md, tags, " +
                "auto_generated_at, manual_updated_at, created_at, updated_at) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
                "ON DUPLICATE KEY UPDATE title=VALUES(title), authors=VALUES(authors), " +
                "published=VALUES(published), abstract_text=VALUES(abstract_text), wiki_md=VALUES(wiki_md), " +
                "tags=VALUES(tags), auto_generated_at=VALUES(auto_generated_at), " +
                "manual_updated_at=VALUES(manual_updated_at), updated_at=VALUES(updated_at)";
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, page.getTitle());
            ps.setString(2, page.getArxivId());
            ps.setString(3, page.getAuthors());
            ps.setObject(4, page.getPublished());
            ps.setString(5, page.getAbstractText());
            ps.setString(6, page.getWikiMd());
            ps.setString(7, page.getTags());
            ps.setObject(8, page.getAutoGeneratedAt());
            ps.setObject(9, page.getManualUpdatedAt());
            ps.setObject(10, page.getCreatedAt());
            ps.setObject(11, page.getUpdatedAt());
            return ps;
        }, keyHolder);
        Long generatedId = Objects.requireNonNull(keyHolder.getKey()).longValue();
        page.setId(generatedId);
        return generatedId;
    }

    public Optional<WikiPage> findById(Long id) {
        String sql = "SELECT * FROM wiki_pages WHERE id = ?";
        List<WikiPage> results = jdbcTemplate.query(sql, new WikiPageRowMapper(), id);
        return results.stream().findFirst();
    }

    public Optional<WikiPage> findByArxivId(String arxivId) {
        String sql = "SELECT * FROM wiki_pages WHERE arxiv_id = ?";
        List<WikiPage> results = jdbcTemplate.query(sql, new WikiPageRowMapper(), arxivId);
        return results.stream().findFirst();
    }

    public List<WikiPage> searchByTags(String tagsQuery, int page, int size) {
        String sql = "SELECT id, title, arxiv_id, authors, published, abstract_text, tags, " +
                "auto_generated_at, manual_updated_at, created_at, updated_at " +
                "FROM wiki_pages " +
                "WHERE MATCH(tags) AGAINST(? IN BOOLEAN MODE) " +
                "ORDER BY published DESC " +
                "LIMIT ? OFFSET ?";
        int offset = page * size;
        return jdbcTemplate.query(sql, new WikiPageRowMapper(), tagsQuery, size, offset);
    }

    public List<WikiPage> findAll(int page, int size) {
        String sql = "SELECT id, title, arxiv_id, authors, published, abstract_text, tags, " +
                "auto_generated_at, manual_updated_at, created_at, updated_at " +
                "FROM wiki_pages ORDER BY published DESC LIMIT ? OFFSET ?";
        int offset = page * size;
        return jdbcTemplate.query(sql, new WikiPageRowMapper(), size, offset);
    }

    public void updateWikiMdByArxivId(String arxivId, String wikiMd) {
        String sql = "UPDATE wiki_pages SET wiki_md = ? WHERE arxiv_id = ?";
        jdbcTemplate.update(sql, wikiMd, arxivId);
    }

    public boolean existsByArxivId(String arxivId) {
        String sql = "SELECT COUNT(*) FROM wiki_pages WHERE arxiv_id = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, arxivId);
        return count != null && count > 0;
    }
}
