package jace.scholarwiki.repository;

import jace.scholarwiki.model.WikiPage;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class WikiPageRowMapper implements RowMapper<WikiPage> {

    @Override
    public WikiPage mapRow(ResultSet rs, int rowNum) throws SQLException {
        WikiPage page = new WikiPage();
        page.setId(rs.getLong("id"));
        page.setTitle(rs.getString("title"));
        page.setArxivId(rs.getString("arxiv_id"));
        page.setAuthors(rs.getString("authors"));
        page.setAbstractText(rs.getString("abstract_text"));
        page.setWikiMd(rs.getString("wiki_md"));
        page.setTags(rs.getString("tags"));

        try {
            page.setPublished(rs.getObject("published", LocalDate.class));
        } catch (SQLException e) {
            page.setPublished(null);
        }
        try {
            page.setAutoGeneratedAt(rs.getObject("auto_generated_at", LocalDateTime.class));
        } catch (SQLException e) {
            page.setAutoGeneratedAt(null);
        }
        try {
            page.setManualUpdatedAt(rs.getObject("manual_updated_at", LocalDateTime.class));
        } catch (SQLException e) {
            page.setManualUpdatedAt(null);
        }
        try {
            page.setCreatedAt(rs.getObject("created_at", LocalDateTime.class));
        } catch (SQLException e) {
            page.setCreatedAt(null);
        }
        try {
            page.setUpdatedAt(rs.getObject("updated_at", LocalDateTime.class));
        } catch (SQLException e) {
            page.setUpdatedAt(null);
        }

        return page;
    }
}
